Add python path
Added environment variable python path pointing to backend/python_scripts
This is an attempt to avoid error:
      AttributeError: module 'get_headers' has no attribute 'find_headers'

Error is likely being caused because get_headers file isn't being identified correctly